prob2: prob2.cpp
	clang++ -std=c++11 prob2.cpp -o prob2.out

prob1: prob1.cpp
	clang++ -std=c++11 prob1.cpp -o prob1.out

prob1.debug: prob1.cpp
	clang++ -g -std=c++11 prob1.cpp -o prob1.out

clean:
	rm -rf *.out *.dSYM
