/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "lib.h"
#include <stdlib.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_RepeatPattern_1(void);
extern void test_RepeatPattern_2(void);
extern void test_RepeatPattern_3(void);
extern void test_duplicate_pattern(void);
extern void test_duplicate_pattern_2(void);
extern void test_duplicate_pattern_3(void);
extern void test_calculate_element(void);
extern void test_calculate_element_1(void);
extern void test_calculate_element_2(void);
extern void test_extend_pattern_1(void);
extern void test_extend_pattern_2(void);
extern void test_extend_pattern_3(void);
extern void test_extend_pattern_4(void);
extern void test_extend_pattern_5(void);
extern void test_extend_pattern_6(void);
extern void test_caculate_phase_1(void);
extern void test_caculate_phase_2(void);
extern void test_caculate_phase_3(void);
extern void test_caculate_phase_4(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestProb1.c");
  run_test(test_RepeatPattern_1, "test_RepeatPattern_1", 9);
  run_test(test_RepeatPattern_2, "test_RepeatPattern_2", 19);
  run_test(test_RepeatPattern_3, "test_RepeatPattern_3", 29);
  run_test(test_duplicate_pattern, "test_duplicate_pattern", 39);
  run_test(test_duplicate_pattern_2, "test_duplicate_pattern_2", 48);
  run_test(test_duplicate_pattern_3, "test_duplicate_pattern_3", 57);
  run_test(test_calculate_element, "test_calculate_element", 66);
  run_test(test_calculate_element_1, "test_calculate_element_1", 74);
  run_test(test_calculate_element_2, "test_calculate_element_2", 82);
  run_test(test_extend_pattern_1, "test_extend_pattern_1", 91);
  run_test(test_extend_pattern_2, "test_extend_pattern_2", 97);
  run_test(test_extend_pattern_3, "test_extend_pattern_3", 103);
  run_test(test_extend_pattern_4, "test_extend_pattern_4", 109);
  run_test(test_extend_pattern_5, "test_extend_pattern_5", 115);
  run_test(test_extend_pattern_6, "test_extend_pattern_6", 121);
  run_test(test_caculate_phase_1, "test_caculate_phase_1", 127);
  run_test(test_caculate_phase_2, "test_caculate_phase_2", 136);
  run_test(test_caculate_phase_3, "test_caculate_phase_3", 145);
  run_test(test_caculate_phase_4, "test_caculate_phase_4", 154);

  return UnityEnd();
}
